Entities\Application:
    repository: Entities\Repositories\Application
    table: applications

    plugins:
        Date:

    fields:
        id:
            isKey: true
        name:
        prefix:
        isEnabled:
        dateCreated:
        dateUpdated: